{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a2d39392-d224-462e-9e7e-b861af2e840b",
   "metadata": {},
   "source": [
    "                                                    ASSIGNMENT EXCEPTION HANDLING PART 2\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "54da20d7-0c14-4153-825d-56ea72d055af",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "227a5495-e9fd-4f0e-9f46-dda980416ecd",
   "metadata": {},
   "source": [
    "   it is recommended to inherit from the base Exception class.\n",
    "   Here's why using the Exception class as the base for custom exceptions is beneficial:\n",
    "   \n",
    "   \n",
    "   1. Standardization: The 'Exception' class provides a standard and consistent way to\n",
    "      handle and raise exceptions in a program. By inheriting from 'Exception',\n",
    "      your custom exception will follow the same conventions and behaviors as built-in exceptions,\n",
    "      making it easier to understand and use in your codebase.\n",
    "      \n",
    "   2. Exception Hierarchy: The Exception class is at the top of the exception hierarchy. \n",
    "      Inheriting from it allows you to create a custom exception that fits within the existing\n",
    "      exception hierarchy and categories. This hierarchy enables developers to catch and handle \n",
    "      exceptions at different levels of specificity, improving code organization and error handling strategies.\n",
    "      \n",
    "      \n",
    "   3. Exception Handling: By using the Exception class, your custom exception can be caught by general exception \n",
    "      handlers. When handling exceptions, it is often useful to have a catch-all exception handler to handle\n",
    "      any unexpected or generic errors. Inheriting from Exception ensures that your custom exception can be\n",
    "      caught by these handlers, making it easier to handle errors uniformly.\n",
    "      \n",
    "   4. Built-in Functionality: The Exception class provides built-in functionality and methods that can be useful\n",
    "      for handling exceptions. For example, you can override the __str__() method to customize the string\n",
    "      representation of your custom exception when it is printed. You can also add additional attributes\n",
    "      or methods to your custom exception class to provide more information or functionality specific to your use case.\n",
    "      \n",
    "      \n",
    "   5. Compatibility: Inheriting from the Exception class ensures compatibility with existing code and libraries that \n",
    "      expect exceptions to be derived from it. Many libraries and frameworks rely on catching and handling exceptions\n",
    "      of the Exception type. By using it as the base class for your custom exception, you ensure compatibility and \n",
    "      integration with these existing tools and practices."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f6d9916c-97c5-455b-acd1-09002247164f",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "696b618a-7169-45a8-a60e-772c69b7993d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The Hierarchy for inbuilt exceptions is: \n",
      " BaseException\n",
      "--- Exception\n",
      "------ TypeError\n",
      "--------- FloatOperation\n",
      "--------- MultipartConversionError\n",
      "------ StopAsyncIteration\n",
      "------ StopIteration\n",
      "------ ImportError\n",
      "--------- ModuleNotFoundError\n",
      "--------- ZipImportError\n",
      "------ OSError\n",
      "--------- ConnectionError\n",
      "------------ BrokenPipeError\n",
      "------------ ConnectionAbortedError\n",
      "------------ ConnectionRefusedError\n",
      "------------ ConnectionResetError\n",
      "--------------- RemoteDisconnected\n",
      "--------- BlockingIOError\n",
      "--------- ChildProcessError\n",
      "--------- FileExistsError\n",
      "--------- FileNotFoundError\n",
      "--------- IsADirectoryError\n",
      "--------- NotADirectoryError\n",
      "--------- InterruptedError\n",
      "------------ InterruptedSystemCall\n",
      "--------- PermissionError\n",
      "--------- ProcessLookupError\n",
      "--------- TimeoutError\n",
      "--------- UnsupportedOperation\n",
      "--------- itimer_error\n",
      "--------- herror\n",
      "--------- gaierror\n",
      "--------- SSLError\n",
      "------------ SSLCertVerificationError\n",
      "------------ SSLZeroReturnError\n",
      "------------ SSLWantWriteError\n",
      "------------ SSLWantReadError\n",
      "------------ SSLSyscallError\n",
      "------------ SSLEOFError\n",
      "--------- Error\n",
      "------------ SameFileError\n",
      "--------- SpecialFileError\n",
      "--------- ExecError\n",
      "--------- ReadError\n",
      "--------- URLError\n",
      "------------ HTTPError\n",
      "------------ ContentTooShortError\n",
      "--------- BadGzipFile\n",
      "------ EOFError\n",
      "--------- IncompleteReadError\n",
      "------ RuntimeError\n",
      "--------- RecursionError\n",
      "--------- NotImplementedError\n",
      "------------ ZMQVersionError\n",
      "------------ StdinNotImplementedError\n",
      "--------- _DeadlockError\n",
      "--------- BrokenBarrierError\n",
      "--------- BrokenExecutor\n",
      "------------ BrokenThreadPool\n",
      "--------- SendfileNotAvailableError\n",
      "--------- ExtractionError\n",
      "--------- VariableError\n",
      "------ NameError\n",
      "--------- UnboundLocalError\n",
      "------ AttributeError\n",
      "--------- FrozenInstanceError\n",
      "------ SyntaxError\n",
      "--------- IndentationError\n",
      "------------ TabError\n",
      "------ LookupError\n",
      "--------- IndexError\n",
      "--------- KeyError\n",
      "------------ NoSuchKernel\n",
      "------------ UnknownBackend\n",
      "--------- CodecRegistryError\n",
      "------ ValueError\n",
      "--------- UnicodeError\n",
      "------------ UnicodeEncodeError\n",
      "------------ UnicodeDecodeError\n",
      "------------ UnicodeTranslateError\n",
      "--------- UnsupportedOperation\n",
      "--------- JSONDecodeError\n",
      "--------- SSLCertVerificationError\n",
      "--------- Error\n",
      "--------- UnsupportedDigestmodError\n",
      "--------- IllegalMonthError\n",
      "--------- IllegalWeekdayError\n",
      "--------- ParserError\n",
      "--------- ClassNotFound\n",
      "--------- ClipboardEmpty\n",
      "--------- MessageDefect\n",
      "------------ NoBoundaryInMultipartDefect\n",
      "------------ StartBoundaryNotFoundDefect\n",
      "------------ CloseBoundaryNotFoundDefect\n",
      "------------ FirstHeaderLineIsContinuationDefect\n",
      "------------ MisplacedEnvelopeHeaderDefect\n",
      "------------ MissingHeaderBodySeparatorDefect\n",
      "------------ MultipartInvariantViolationDefect\n",
      "------------ InvalidMultipartContentTransferEncodingDefect\n",
      "------------ UndecodableBytesDefect\n",
      "------------ InvalidBase64PaddingDefect\n",
      "------------ InvalidBase64CharactersDefect\n",
      "------------ InvalidBase64LengthDefect\n",
      "------------ HeaderDefect\n",
      "--------------- InvalidHeaderDefect\n",
      "--------------- HeaderMissingRequiredValue\n",
      "--------------- NonPrintableDefect\n",
      "--------------- ObsoleteHeaderDefect\n",
      "--------------- NonASCIILocalPartDefect\n",
      "--------------- InvalidDateDefect\n",
      "--------- MacroToEdit\n",
      "--------- InvalidFileException\n",
      "--------- UnequalIterablesError\n",
      "--------- InvalidVersion\n",
      "--------- _InvalidELFFileHeader\n",
      "--------- InvalidWheelFilename\n",
      "--------- InvalidSdistFilename\n",
      "--------- InvalidSpecifier\n",
      "--------- InvalidMarker\n",
      "--------- UndefinedComparison\n",
      "--------- UndefinedEnvironmentName\n",
      "--------- InvalidRequirement\n",
      "------------ RequirementParseError\n",
      "--------- InvalidVersion\n",
      "------ AssertionError\n",
      "------ ArithmeticError\n",
      "--------- FloatingPointError\n",
      "--------- OverflowError\n",
      "--------- ZeroDivisionError\n",
      "------------ DivisionByZero\n",
      "------------ DivisionUndefined\n",
      "--------- DecimalException\n",
      "------------ Clamped\n",
      "------------ Rounded\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Inexact\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Subnormal\n",
      "--------------- Underflow\n",
      "------------ DivisionByZero\n",
      "------------ FloatOperation\n",
      "------------ InvalidOperation\n",
      "--------------- ConversionSyntax\n",
      "--------------- DivisionImpossible\n",
      "--------------- DivisionUndefined\n",
      "--------------- InvalidContext\n",
      "------ SystemError\n",
      "--------- CodecRegistryError\n",
      "------ ReferenceError\n",
      "------ MemoryError\n",
      "------ BufferError\n",
      "------ Warning\n",
      "--------- UserWarning\n",
      "------------ GetPassWarning\n",
      "------------ FormatterWarning\n",
      "--------- EncodingWarning\n",
      "--------- DeprecationWarning\n",
      "------------ ProvisionalWarning\n",
      "--------- PendingDeprecationWarning\n",
      "--------- SyntaxWarning\n",
      "--------- RuntimeWarning\n",
      "------------ ProactorSelectorThreadWarning\n",
      "------------ UnknownTimezoneWarning\n",
      "------------ PEP440Warning\n",
      "--------- FutureWarning\n",
      "------------ ProvisionalCompleterWarning\n",
      "--------- ImportWarning\n",
      "--------- UnicodeWarning\n",
      "--------- BytesWarning\n",
      "--------- ResourceWarning\n",
      "--------- DeprecatedTzFormatWarning\n",
      "--------- PkgResourcesDeprecationWarning\n",
      "------ _OptionError\n",
      "------ _Error\n",
      "------ error\n",
      "------ Verbose\n",
      "------ Error\n",
      "------ SubprocessError\n",
      "--------- CalledProcessError\n",
      "--------- TimeoutExpired\n",
      "------ TokenError\n",
      "------ StopTokenizing\n",
      "------ ClassFoundException\n",
      "------ EndOfBlock\n",
      "------ TraitError\n",
      "------ Error\n",
      "------ Error\n",
      "--------- CancelledError\n",
      "--------- TimeoutError\n",
      "--------- InvalidStateError\n",
      "------ _GiveupOnSendfile\n",
      "------ error\n",
      "------ Incomplete\n",
      "------ TimeoutError\n",
      "------ InvalidStateError\n",
      "------ LimitOverrunError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ Empty\n",
      "------ Full\n",
      "------ ArgumentError\n",
      "------ ZMQBaseError\n",
      "--------- ZMQError\n",
      "------------ ContextTerminated\n",
      "------------ Again\n",
      "------------ InterruptedSystemCall\n",
      "--------- ZMQBindError\n",
      "--------- NotDone\n",
      "------ PickleError\n",
      "--------- PicklingError\n",
      "--------- UnpicklingError\n",
      "------ _Stop\n",
      "------ ArgumentError\n",
      "------ ArgumentTypeError\n",
      "------ ConfigError\n",
      "--------- ConfigLoaderError\n",
      "------------ ArgumentError\n",
      "--------- ConfigFileNotFound\n",
      "------ ConfigurableError\n",
      "--------- MultipleInstanceError\n",
      "------ ApplicationError\n",
      "------ error\n",
      "------ TimeoutError\n",
      "------ error\n",
      "------ ReturnValueIgnoredError\n",
      "------ KeyReuseError\n",
      "------ UnknownKeyError\n",
      "------ LeakedCallbackError\n",
      "------ BadYieldError\n",
      "------ ReturnValueIgnoredError\n",
      "------ Return\n",
      "------ InvalidPortNumber\n",
      "------ error\n",
      "------ LZMAError\n",
      "------ RegistryError\n",
      "------ _GiveupOnFastCopy\n",
      "------ Error\n",
      "--------- NoSectionError\n",
      "--------- DuplicateSectionError\n",
      "--------- DuplicateOptionError\n",
      "--------- NoOptionError\n",
      "--------- InterpolationError\n",
      "------------ InterpolationMissingOptionError\n",
      "------------ InterpolationSyntaxError\n",
      "------------ InterpolationDepthError\n",
      "--------- ParsingError\n",
      "------------ MissingSectionHeaderError\n",
      "------ NoIPAddresses\n",
      "------ BadZipFile\n",
      "------ LargeZipFile\n",
      "------ BadEntryPoint\n",
      "------ NoSuchEntryPoint\n",
      "------ DuplicateKernelError\n",
      "------ ErrorDuringImport\n",
      "------ NotOneValueFound\n",
      "------ CannotEval\n",
      "------ OptionError\n",
      "------ BdbQuit\n",
      "------ Restart\n",
      "------ ExceptionPexpect\n",
      "--------- EOF\n",
      "--------- TIMEOUT\n",
      "------ PtyProcessError\n",
      "------ FindCmdError\n",
      "------ HomeDirError\n",
      "------ ProfileDirError\n",
      "------ IPythonCoreError\n",
      "--------- TryNext\n",
      "--------- UsageError\n",
      "--------- StdinNotImplementedError\n",
      "------ InputRejected\n",
      "------ GetoptError\n",
      "------ ErrorToken\n",
      "------ PrefilterError\n",
      "------ AliasError\n",
      "--------- InvalidAliasError\n",
      "------ Error\n",
      "--------- InterfaceError\n",
      "--------- DatabaseError\n",
      "------------ InternalError\n",
      "------------ OperationalError\n",
      "------------ ProgrammingError\n",
      "------------ IntegrityError\n",
      "------------ DataError\n",
      "------------ NotSupportedError\n",
      "------ Warning\n",
      "------ SpaceInInput\n",
      "------ DOMException\n",
      "--------- IndexSizeErr\n",
      "--------- DomstringSizeErr\n",
      "--------- HierarchyRequestErr\n",
      "--------- WrongDocumentErr\n",
      "--------- InvalidCharacterErr\n",
      "--------- NoDataAllowedErr\n",
      "--------- NoModificationAllowedErr\n",
      "--------- NotFoundErr\n",
      "--------- NotSupportedErr\n",
      "--------- InuseAttributeErr\n",
      "--------- InvalidStateErr\n",
      "--------- SyntaxErr\n",
      "--------- InvalidModificationErr\n",
      "--------- NamespaceErr\n",
      "--------- InvalidAccessErr\n",
      "--------- ValidationErr\n",
      "------ ValidationError\n",
      "------ EditReadOnlyBuffer\n",
      "------ _Retry\n",
      "------ InvalidLayoutError\n",
      "------ HeightIsUnknownError\n",
      "------ ParserSyntaxError\n",
      "------ InternalParseError\n",
      "------ _PositionUpdatingFinished\n",
      "------ SimpleGetItemNotFound\n",
      "------ UncaughtAttributeError\n",
      "------ HasNoContext\n",
      "------ ParamIssue\n",
      "------ _JediError\n",
      "--------- InternalError\n",
      "--------- WrongVersion\n",
      "--------- RefactoringError\n",
      "------ OnErrorLeaf\n",
      "------ InvalidPythonEnvironment\n",
      "------ MessageError\n",
      "--------- MessageParseError\n",
      "------------ HeaderParseError\n",
      "------------ BoundaryError\n",
      "--------- MultipartConversionError\n",
      "--------- CharsetError\n",
      "------ Error\n",
      "------ HTTPException\n",
      "--------- NotConnected\n",
      "--------- InvalidURL\n",
      "--------- UnknownProtocol\n",
      "--------- UnknownTransferEncoding\n",
      "--------- UnimplementedFileMode\n",
      "--------- IncompleteRead\n",
      "--------- ImproperConnectionState\n",
      "------------ CannotSendRequest\n",
      "------------ CannotSendHeader\n",
      "------------ ResponseNotReady\n",
      "--------- BadStatusLine\n",
      "------------ RemoteDisconnected\n",
      "--------- LineTooLong\n",
      "------ InteractivelyDefined\n",
      "------ KillEmbedded\n",
      "------ Error\n",
      "--------- NoSuchProcess\n",
      "------------ ZombieProcess\n",
      "--------- AccessDenied\n",
      "--------- TimeoutExpired\n",
      "------ _Ipv6UnsupportedError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ DebuggerInitializationError\n",
      "------ ExpatError\n",
      "------ Error\n",
      "--------- ProtocolError\n",
      "--------- ResponseError\n",
      "--------- Fault\n",
      "------ ParseBaseException\n",
      "--------- ParseException\n",
      "--------- ParseFatalException\n",
      "------------ ParseSyntaxException\n",
      "------ RecursiveGrammarException\n",
      "------ ResolutionError\n",
      "--------- VersionConflict\n",
      "------------ ContextualVersionConflict\n",
      "--------- DistributionNotFound\n",
      "--------- UnknownExtra\n",
      "------ _Error\n",
      "------ UnableToResolveVariableException\n",
      "------ InvalidTypeInArgsException\n",
      "--- GeneratorExit\n",
      "--- SystemExit\n",
      "--- KeyboardInterrupt\n",
      "--- CancelledError\n",
      "--- AbortThread\n"
     ]
    }
   ],
   "source": [
    "import inspect\n",
    "\n",
    "def tree_class(cls, ind=0):\n",
    "  print('-' * ind, cls.__name__)\n",
    "  for K in cls.__subclasses__():\n",
    "    tree_class(K, ind + 3)\n",
    "\n",
    "print(\"The Hierarchy for inbuilt exceptions is: \")\n",
    "inspect.getclasstree(inspect.getmro(BaseException))\n",
    "tree_class(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "741dfb04-eb92-48d8-b48f-ce850a0d3eb4",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2c01a1d9-5c22-4abf-81c2-87d19724d21a",
   "metadata": {},
   "source": [
    "    ArithmeticError class in Python is the base class for exceptions that occur during arithmetic operations.\n",
    "                    It serves as a parent class for specific arithmetic-related exceptions. \n",
    "                    Here are two common errors defined in the ArithmeticError class, \n",
    "                    along with explanations and examples:\n",
    "                    \n",
    "                    \n",
    "       1. ZeroDivisionError: This exception is raised when division or modulo operation is performed with a divisor of zero.\n",
    "                "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1e8acef5-7a44-44d8-bd74-56ffa21f592a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero!\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7f794160-d70e-42b8-ae6b-0e4e60600147",
   "metadata": {},
   "source": [
    "      2. OverflowError: This exception is raised when the result of an arithmetic operation exceeds the maximum \n",
    "       representable value for a numeric type."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "67d90c29-5fa0-4f02-bcf7-a8ef9bdb77f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "try:\n",
    "    result = sys.maxsize + 1\n",
    "except OverflowError:\n",
    "    print(\"Error: Integer overflow\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "408e4b1e-09ae-4e88-9a19-b128ad5e160b",
   "metadata": {},
   "source": [
    "Error: Integer overflow!"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3705d6e5-7695-49aa-9f32-85c2b911a5f4",
   "metadata": {},
   "source": [
    "   sys.maxsize represents the maximum value that an integer can hold on the current platform.\n",
    "    By adding 1 to it, we exceed the maximum representable value,\n",
    "    causing an OverflowError to be raised. The corresponding exception block is executed,\n",
    "    printing an error message."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "369e14f8-b854-4440-a084-6fddbcbb617f",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dd04372b-487c-4641-93c4-c3cd217482a1",
   "metadata": {},
   "source": [
    "LookupError class in Python is the base class for exceptions that occur when a lookup \n",
    "     or indexing operation fails.\n",
    "     It serves as a parent class for specific lookup-related exceptions.\n",
    "     Here are two commonly used exceptions derived from LookupError: \n",
    "     \n",
    "     \n",
    "  1. KeyError: This exception is raised when a dictionary key or a set element is not found during a lookup operation.\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "ee4c13ad-79ca-4001-94c8-d668d95c0610",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key not found in the dictionary!\n"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']\n",
    "except KeyError:\n",
    "    print(\"Error: Key not found in the dictionary\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d8532c75-1145-4331-8d73-bd7641e70669",
   "metadata": {},
   "source": [
    "   example:- we attempt to access the key 'd' in the my_dict dictionary using the square bracket notation.\n",
    "           However, the key does not exist in the dictionary, causing a KeyError to be raised.\n",
    "           The corresponding exception block is executed, printing an error message. \n",
    "            \n",
    "            \n",
    "    2. IndexError:- This exception is raised when an index is out of range while accessing elements from a sequence (e.g, list, tuple, string)."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c41edcf3-bd59-4f18-b00d-7ce055299182",
   "metadata": {},
   "source": [
    "Example 2 - IndexError with a list:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "de28bfb6-f21d-4aca-bc62-52e7a9dd421a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Index is out of range!\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[3]\n",
    "except IndexError:\n",
    "    print(\"Error: Index is out of range\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f5a3fdc3-9995-47f7-8de7-2e54a76c361f",
   "metadata": {},
   "source": [
    "    example, we try to access the element at index 3 in the my_list list. However, the list contains only three elements,\n",
    "             and indices start from 0, so index 3 is out of range. As a result, an IndexError is raised, and the corresponding\n",
    "             exception block is executed, printing an error message.\n",
    "\n",
    "    Both KeyError and IndexError are derived from the LookupError class. By catching these specific exceptions, \n",
    "             you can handle lookup-related errors more precisely. For example, you can provide alternative values \n",
    "             or fallback logic when a key or index is not found, or you can inform the user about the error in a user-friendly manner."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df9d2838-7165-48da-9d6e-82fcfd002dd9",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7f32df6e-0009-452a-af62-15a29210f293",
   "metadata": {},
   "source": [
    "ImportError is a built-in exception class in Python that is raised when an imported module, package,\n",
    "            or object cannot be found or loaded. It occurs during the import statement execution when\n",
    "            Python encounters an error while trying to import a module.\n",
    "\n",
    "    ImportError exception can be raised in various scenarios, such :\n",
    "\n",
    "       1.The specified module does not exist in the Python environment.\n",
    "       2.The module is not installed or accessible.\n",
    "       3. There is a circular import, where two or more modules depend on each other."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "3bff6eb7-d728-462b-972a-93a8bfe13055",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found or cannot be imported!\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Module not found or cannot be imported!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b2805fb2-6e9a-4825-99f3-776e5201db4d",
   "metadata": {},
   "source": [
    "  example:- the import non_existent_module statement tries to import a module named \"non_existent_module\"\n",
    "            that does not exist. As a result, an ImportError is raised, and the corresponding exception block\n",
    "            is executed, printing an error message.\n",
    "\n",
    "  On the other hand, ModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6.\n",
    "            It specifically represents an error when a module or package cannot be found during the import process.\n",
    "            It provides more specific information about the module not being found."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "58f4daa4-e784-400d-8331-e1f014e1c01d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found!\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Error: Module not found!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0908f76f-f95d-4663-87d5-e2c2fddbe18b",
   "metadata": {},
   "source": [
    "  example, the code raises a ModuleNotFoundError because the specified module \"non_existent_module\" is not\n",
    "           found during the import statement.\n",
    "\n",
    "  In summary, ImportError is a more general exception class that encompasses all import-related errors, \n",
    "            including the inability to find or load modules. ModuleNotFoundError is a subclass of ImportError \n",
    "   "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c388bff0-be6c-49d1-a4f2-cb8edd82aa29",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e01414ee-9040-41fd-a910-f4aed4c67e9b",
   "metadata": {},
   "source": [
    "  1. Be specific in exception catching: Catch exceptions at the appropriate level of specificity.\n",
    "     Avoid catching broad exceptions like Exception unless you have a compelling reason.\n",
    "     Catching specific exceptions allows you to handle different types of errors differently\n",
    "     and provides more meaningful error messages.\n",
    "     \n",
    "  2. Use multiple except blocks: Use multiple except blocks to handle different types of exceptions separately.\n",
    "     This allows you to provide specific handling logic for each type of exception.\n",
    "     \n",
    "  3. Handle exceptions gracefully: Provide clear and informative error messages to users when an exception occurs.\n",
    "     Avoid exposing sensitive information in error messages.\n",
    "     Use logging or error tracking systems to capture detailed error information for debugging purposes.\n",
    "     \n",
    "  4. Avoid bare except statements: Avoid using bare except statements without specifying the exception type. \n",
    "     This can mask errors and make debugging difficult. Only catch the exceptions you expect and know how to handle.\n",
    "     \n",
    "  5. Use the finally block: Use the finally block to ensure that cleanup code is executed, regardless of whether an \n",
    "     exception occurred or not. Common use cases for finally blocks include releasing resources\n",
    "     (e.g., closing files, database connections) or restoring system states.\n",
    "     \n",
    "  6. Consider using context managers: Use context managers (with statement) when working with resources that need to\n",
    "      be properly managed, such as files or database connections. Context managers automatically handle resource\n",
    "     cleanup, even in the presence of exceptions.\n",
    "     \n",
    "     \n",
    "  7. Use custom exception classes: Create custom exception classes to represent specific errors or situations relevant \n",
    "     to your application. This can make your code more readable and allow for specialized exception handling."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "efd49c1d-5a71-4e67-b429-2d4205344612",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
